# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FGgWiR5Cbk2TuipJxHdmEOuYGR2_EcEw
"""

import tensorflow as tf

from tensorflow.keras import datasets

from tensorflow.keras import layers

from tensorflow.keras import models

import matplotlib.pyplot as plt

(train_images,train_labels) , (test_images, test_labels) = datasets.cifar10.load_data()

train_images , test_images = train_images/255.0 , test_images/255.0

class_names =['avion', 'voiture', 'oiseau', 'chat', 'cerf', 'chien', 'grenouille', 'cheval', 'patou', 'camion']

plt.figure(figsize= (10, 10))

for i in range(25):
  plt.subplot(5, 5, i+1)
  plt.xticks([])
  plt.yticks([])

  plt.imshow(train_images[i], cmap  = plt.cm.binary)

  plt.xlabel(class_names[train_labels[i][0]])

  plt.show

model = models.Sequential()

model.add(layers.Conv2D(32, (3,3), activation = 'relu' , input_shape = (32, 32, 3)))

model.add(layers.MaxPooling2D(2, 2))

model.add(layers.Conv2D(64, (3, 3), activation = 'relu'))

model.add(layers.MaxPooling2D(2, 2))

model.add(layers.Conv2D(64, (3, 3), activation = 'relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))
model.summary()

model.compile(optimizer='adam', 
    metrics=['accuracy'],loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits =True ))

history = model.fit(train_images, train_labels, epochs = 10, validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label ='accuracy')

plt.plot(history.history['val_accuracy'], label= 'val_accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc = 'lower right')